/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bihe0832_android_lib_crop_jni_CropAction */

#ifndef _Included_com_bihe0832_android_lib_crop_jni_CropAction
#define _Included_com_bihe0832_android_lib_crop_jni_CropAction
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_bihe0832_android_lib_crop_jni_CropAction
* Method:    cropCImg
* Signature: (Ljava/lang/String;Ljava/lang/String;IIIIF)Z
*/
JNIEXPORT jboolean JNICALL Java_com_bihe0832_android_lib_crop_jni_CropAction_crop
(JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jfloat, jfloat, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
